<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Key parameters (numeric/string config used by the application).
    | Keys defined here appear on the Settings page and can be overridden.
    | Defaults are used when no value is stored in the database.
    |--------------------------------------------------------------------------
    */
    'parameters' => [
        'default_allocation' => [
            'label' => 'Default member allocation ($)',
            'help' => 'Default allowed_allocation for new members and when not set. Used for contributions and projections.',
            'default' => '500',
            'type' => 'integer',
        ],
        'collections_due_day' => [
            'label' => 'Collections due day',
            'help' => 'Day of the month (1–31) when contributions and loan repayments are due (e.g. 5 = 5th of next month).',
            'default' => '5',
            'type' => 'integer',
        ],
        'max_projection_months' => [
            'label' => 'Max projection months',
            'help' => 'Maximum months to project when calculating "when will we reach target" balance.',
            'default' => '120',
            'type' => 'integer',
        ],
        'app_display_name' => [
            'label' => 'Application display name',
            'help' => 'Name shown in the UI (reports, emails). Leave empty to use APP_NAME from .env.',
            'default' => '',
            'type' => 'string',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Templates (text content used by the application: emails, reports, etc.).
    | Placeholders like {member_name}, {amount} can be documented in help.
    |--------------------------------------------------------------------------
    */
    'templates' => [
        'email_payment_reminder' => [
            'label' => 'Payment reminder email',
            'help' => 'Body template for loan payment reminder. Placeholders: {member_name}, {amount}, {due_date}, {loan_id}.',
            'default' => "Hello {member_name},\n\nYour loan payment of {amount} is due on {due_date} (Loan: {loan_id}).\n\nPlease ensure sufficient balance in your account.",
        ],
        'email_loan_approved' => [
            'label' => 'Loan approved notification',
            'help' => 'Body template when a loan is approved. Placeholders: {member_name}, {amount}, {loan_id}.',
            'default' => "Hello {member_name},\n\nYour loan application ({loan_id}) for {amount} has been approved. You will receive the disbursement according to the queue.",
        ],
        'report_footer' => [
            'label' => 'Report footer',
            'help' => 'Text appended to generated reports. Placeholders: {app_name}, {generated_at}.',
            'default' => "Generated by {app_name} on {generated_at}.",
        ],
        'exception_sla_notification' => [
            'label' => 'Exception SLA notification',
            'help' => 'Body when an exception reaches SLA. Placeholders: {exception_id}, {description}, {created_at}.',
            'default' => "Exception #{exception_id} has reached its SLA threshold.\nDescription: {description}\nCreated: {created_at}",
        ],
        'import_excel_mapping' => [
            'label' => 'Import Excel/CSV column mapping',
            'help' => 'JSON: column indices (1-based) for bank statement Excel. Keys: start_row, col_date, col_transaction_type, col_description_d, col_description_e, col_amount, col_balance. E.g. B=2, C=3, D=4, E=5, F=6, H=8. Leave as default for standard layout.',
            'default' => '{"start_row":6,"col_date":2,"col_transaction_type":3,"col_description_d":4,"col_description_e":5,"col_amount":6,"col_balance":8}',
        ],
        'import_success_message' => [
            'label' => 'Import success message',
            'help' => 'Message shown after importing bank transactions. Placeholders: {imported_count}, {duplicate_count}, {total_count}. Leave empty to use built-in message.',
            'default' => '',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Dashboard widgets (toggle visibility per panel).
    | Keys here map to widget classes (admin) or Blade sections (member).
    |--------------------------------------------------------------------------
    */
    'dashboard_widgets' => [
        'admin' => [
            'quick_actions'         => ['label' => 'Quick Actions',              'default' => true],
            'stats_overview'        => ['label' => 'Stats Overview',             'default' => true],
            'open_exceptions'       => ['label' => 'Open Exceptions',            'default' => true],
            'reconciliation_status' => ['label' => 'Reconciliation Status',      'default' => true],
            'cash_flow_trend_chart' => ['label' => 'Cash Flow Trend Chart',      'default' => true],
            'collections_progress'  => ['label' => 'Collections Progress Gauge', 'default' => true],
            'delinquent_loans'      => ['label' => 'Delinquent Loans',           'default' => true],
            'pending_loan_queue'    => ['label' => 'Pending Loan Queue',         'default' => true],
            'external_bank_imports' => ['label' => 'External Bank Imports',      'default' => true],
            'balance_integrity'     => ['label' => 'Balance Integrity Check',    'default' => true],
            'upcoming_payments'     => ['label' => 'Upcoming Payments Calendar', 'default' => true],
            'recent_transactions'   => ['label' => 'Recent Transactions',        'default' => true],
        ],
        'member' => [
            'summary_cards'        => ['label' => 'Summary Cards',             'default' => true],
            'upcoming_obligations' => ['label' => 'Upcoming Obligations',      'default' => true],
            'loan_progress'        => ['label' => 'Loan Repayment Progress',   'default' => true],
            'loan_eligibility'     => ['label' => 'Loan Eligibility',          'default' => true],
            'contribution_history' => ['label' => 'Contribution History',      'default' => true],
            'fund_growth'          => ['label' => 'Fund Growth Chart',         'default' => true],
            'collections_status'   => ['label' => 'Collections Status',        'default' => true],
            'dependants'           => ['label' => 'Dependant Summary',         'default' => true],
            'recent_activity'      => ['label' => 'Recent Activity',           'default' => true],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Loan Tiers (Definition of allowability based on member activity).
    |--------------------------------------------------------------------------
    */
    'loan_tiers' => [
        [
            'name' => 'Tier 1',
            'min_amount' => 1000,
            'max_amount' => 30000,
            'installment_amount' => 1000,
            'maturity_percentage' => 16,
            'allocation_percentage' => 10,
            'term_months' => 12,
            'interest_rate' => 0,
        ],
        [
            'name' => 'Tier 2',
            'min_amount' => 31000,
            'max_amount' => 60000,
            'installment_amount' => 1500,
            'maturity_percentage' => 16,
            'allocation_percentage' => 10,
            'term_months' => 12,
            'interest_rate' => 0,
        ],
        [
            'name' => 'Tier 3',
            'min_amount' => 61000,
            'max_amount' => 90000,
            'installment_amount' => 2000,
            'maturity_percentage' => 16,
            'allocation_percentage' => 10,
            'term_months' => 12,
            'interest_rate' => 0,
        ],
        [
            'name' => 'Tier 4',
            'min_amount' => 91000,
            'max_amount' => 120000,
            'installment_amount' => 2500,
            'maturity_percentage' => 16,
            'allocation_percentage' => 10,
            'term_months' => 12,
            'interest_rate' => 0,
        ],
        [
            'name' => 'Tier 5',
            'min_amount' => 121000,
            'max_amount' => 150000,
            'installment_amount' => 3000,
            'maturity_percentage' => 16,
            'allocation_percentage' => 10,
            'term_months' => 12,
            'interest_rate' => 0,
        ],
        [
            'name' => 'Tier 6',
            'min_amount' => 151000,
            'max_amount' => 180000,
            'installment_amount' => 3500,
            'maturity_percentage' => 16,
            'allocation_percentage' => 10,
            'term_months' => 12,
            'interest_rate' => 0,
        ],
        [
            'name' => 'Tier 7',
            'min_amount' => 181000,
            'max_amount' => 210000,
            'installment_amount' => 4000,
            'maturity_percentage' => 16,
            'allocation_percentage' => 10,
            'term_months' => 12,
            'interest_rate' => 0,
        ],
        [
            'name' => 'Tier 8',
            'min_amount' => 211000,
            'max_amount' => 240000,
            'installment_amount' => 4500,
            'maturity_percentage' => 16,
            'allocation_percentage' => 10,
            'term_months' => 12,
            'interest_rate' => 0,
        ],
        [
            'name' => 'Tier 9',
            'min_amount' => 241000,
            'max_amount' => 270000,
            'installment_amount' => 5000,
            'maturity_percentage' => 16,
            'allocation_percentage' => 10,
            'term_months' => 12,
            'interest_rate' => 0,
        ],
        [
            'name' => 'Tier 10',
            'min_amount' => 271000,
            'max_amount' => 300000,
            'installment_amount' => 5500,
            'maturity_percentage' => 16,
            'allocation_percentage' => 10,
            'term_months' => 12,
            'interest_rate' => 0,
        ],
    ],
];
